### ISSUE TITLE
Definir o Tema do nosso projeto.

### ISSUE THREAD

**Issue by henrikeSilva93** [rodrigovale05/ADS031#2]
Precisamos definir o tema do nosso projeto. 
O objetivo é que  o projeto seja uma coisa simples, sem features mirabolantes e o Layout vai ser essencial.

**Comment by henrikeSilva93** [comment]
Agora que definimos o tema, devemos fazer a prototipagem da tela pelo figma

**Comment by fidelis33** [comment]
Alguma sugestão de como iniciar a prototipagem ?

**Comment by henrikeSilva93** [comment]
Vamos fazer uma call esse fds e começar a definir. o Ideal é que todos estejam online para que todos possam sugerir e contribuir.

**Comment by fidelis33** [comment]
tranquilo, sabado e domingo estou disponivel durante o dia

**Comment by veras007** [comment]
fechado para sábado ou domingo?
