### ISSUE TITLE
Prototipação do Programa

### ISSUE THREAD

**Issue by rodrigovale05** [rodrigovale05/ADS031#3]

**Comment by rodrigovale05** [comment]
TODOS tem que participar dessa parte do projeto.
TODOS irão criar suas telas, com as suas ideias no figma.com.
DOMINGO dia 12/09/2021 a gente vai se juntar e analisar as opções.

**Comment by rodrigovale05** [comment]
Esse aqui é o meu protótipo para a decisão desse domingo
https://www.figma.com/file/2QORsVMu066OTcA35hVV7f/PRIMEIRO-TESTE?node-id=0%3A1

**Comment by henrikeSilva93** [comment]
Pessoal, comecei criando uma tela, fiz uma slash, tela de login e cadastro. Se gostarem da identidade visual dela, posso continuar trabalhando.
https://www.figma.com/file/pBKKhTCVQpyn8hd2oGouo5/Untitled?node-id=0%3A1

me deem o feedback de vcs

**Comment by henrikeSilva93** [comment]
![telasiniciais](https://user-images.githubusercontent.com/53267575/133354855-530ba824-915d-4f5f-9176-1d44d1bef764.PNG)

**Comment by fidelis33** [comment]
Galera alterei uma tela, e criei uma nova, também coloquei as etapas que o app ira seguir. 


https://www.figma.com/file/sxZ8LyXmYB6rOizuFcYCQW/Untitled?node-id=0%3A1

**Comment by henrikeSilva93** [comment]
Galera, finalizei meu protótipo
https://www.figma.com/file/pBKKhTCVQpyn8hd2oGouo5/Untitled?node-id=0%3A1

**Comment by rodrigovale05** [comment]
https://www.figma.com/file/tXKYWbzQG3GI33jJETh0fw/PROT%C3%93TIPO-FINALIZADO?node-id=0%3A1

ESSE É O LINK DO PROTÓTIPO FINALIZADO
Participações:
Áquila Henrique Silva Faria
Artur De Souza Fidelis
Gustavo Veras
Rodrigo Costa Gomes Vale
